all: clean install 

install: 
	gcc -o0 main.c -o main

opt_l1: 
	gcc -o1 main.c -o main
	
opt_l2: 
	gcc -o2 main.c -o main
	
opt_l3: 
	gcc -o3 main.c -o main
	
clean:
	rm -rf main *.txt
	
matmul:
	./main 0 2000

foo1:
	./main 1 10000
